"""The committed schemas in src/dug_data_model/schemas/ must match the models.

The build hook regenerates them on every build, but the copies in the repository are only
regenerated by hand, so this catches a model change that forgot to.
"""

import json
from pathlib import Path

from dug_data_model import v2
from dug_data_model.scaffold.utils import generate_json_schema, generate_markdown_schema

SCHEMAS = Path(v2.__file__).parent.parent / "schemas"
TITLE = "Dug Data Model v2"


def test_committed_json_schema_is_up_to_date():
    committed = json.loads((SCHEMAS / "v2_schema.json").read_text())
    assert committed == generate_json_schema(v2.DugElementParsedList, title=TITLE)


def test_committed_markdown_schema_is_up_to_date():
    committed = (SCHEMAS / "v2_schema.md").read_text()
    assert committed == generate_markdown_schema(v2.DugElementParsedList, title=TITLE)
